package csed.swe.studentunity.model;

public enum RegistrationResponses {
    SUCCESSFUL_REGISTRATION,
    USER_NEEDS_VERIFICATION,
    USER_IS_NOT_REGISTERED,
    SUCCESSFUL_VERIFICATION,
    FAILED_VERIFICATION,
    USER_ALREADY_EXISTS
}
