name: Student Unity frontend workflow

on:
  push:
    paths:
      - 'Student-Unity-frontend/**'
      - '.github/workflows/**'
    branches:
      - master

  pull_request:
    paths:
      - 'Student-Unity-frontend/**'
      - '.github/workflows/**'
    types:
      - opened
      - synchronize
      - reopened
  
jobs:
  sonarcloud: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: Student-Unity-frontend
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_UI }}
